### ISSUE TITLE
Remove nasty traceback on KeyboardInterrupt and EOFError in input

### ISSUE THREAD

**Issue by ChaoticRoman** [ChaoticRoman/chatgpt-gui#15]
There is a stack trace when you quit the CLI using CTRL+C or CTRL+D, this should be caught and the app should quit silently...

The fix should be handled entirely in `cli.py` as core should be UI frontend independent.

**Comment by Halzorg** [comment]
I would like to attempt to fix this issue. Could you please assign it to me?

**Comment by ChaoticRoman** [comment]
Hi, @Halzorg! Of course, let me do it. Thank you for interest in contributing.

**Comment by ChaoticRoman** [comment]
About assisting, the way how to do this is put `try...except` blog catching specifically two exceptions: `KeyboardInterrupt` and `EOFError`. Except blog would be with `pass` only, `try` blog should be always as minimal as possible, in this case it would be around `input` builtin function call in `cli.py`.
